### ISSUE TITLE
Segfault when clicking "New" after opening an existing scxml file or deleting current one

### ISSUE THREAD

**Issue by bweir** [KDAB/KDStateMachineEditor#4]
Got it working and this is the generate result. Otherwise, it's looking awesome. :D

```
./bin/kdstatemachineeditor 
QML debugging is enabled. Only use this in a safe environment.
kdsme.view: void KDSME::StateMachineScene::layout() KDSME::LayerwiseLayouter(0x18e2850) State[this=0x197bc50, label="New"]
kdsme.core: virtual QRectF KDSME::LayerwiseLayouter::layout(KDSME::State*, const KDSME::LayoutProperties*) Took 0 ms
kdsme.view: void KDSME::StateMachineScene::layout() KDSME::LayerwiseLayouter(0x18e2850) State[this=0x197bc50, label="New"]
kdsme.core: virtual QRectF KDSME::LayerwiseLayouter::layout(KDSME::State*, const KDSME::LayoutProperties*) Took 0 ms
kdsme.view: void KDSME::StateMachineScene::layout() KDSME::LayerwiseLayouter(0x18e2850) State[this=0x1f55a00, label="New"]
kdsme.core: virtual QRectF KDSME::LayerwiseLayouter::layout(KDSME::State*, const KDSME::LayoutProperties*) Took 0 ms
kdsme.view: void KDSME::StateMachineScene::layout() KDSME::LayerwiseLayouter(0x18e2850) State[this=0x2016690, label="basicstate"]
kdsme.core: virtual QRectF KDSME::LayerwiseLayouter::layout(KDSME::State*, const KDSME::LayoutProperties*) Took 8 ms
Segmentation fault (core dumped)
```

**Comment by krf** [comment]
@bweir A backtrace would be very helpful here.

Could you run the exeutable through a debugger and post the backtrace?

**Comment by bweir** [comment]
Hi @krf, here you go.

```
(gdb) run
Starting program: /home/brett/KDStateMachineEditor/build/bin/kdstatemachineeditor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
QML debugging is enabled. Only use this in a safe environment.
[New Thread 0x7fffde9cb700 (LWP 4634)]
kdsme.view: void KDSME::StateMachineScene::layout() KDSME::LayerwiseLayouter(0xa8d6d0) State[this=0xb26b90, label="New"]
kdsme.core: virtual QRectF KDSME::LayerwiseLayouter::layout(KDSME::State*, const KDSME::LayoutProperties*) Took 0 ms
kdsme.view: void KDSME::StateMachineScene::layout() KDSME::LayerwiseLayouter(0xa8d6d0) State[this=0x11b8360, label="qtstickman"]
kdsme.core: virtual QRectF KDSME::LayerwiseLayouter::layout(KDSME::State*, const KDSME::LayoutProperties*) Took 42 ms
[New Thread 0x7fffeb48a700 (LWP 4633)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff760cda9 in QV4::QObjectWrapper::wrap(QV4::ExecutionEngine*, QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
(gdb) backtrace
#0  0x00007ffff760cda9 in QV4::QObjectWrapper::wrap(QV4::ExecutionEngine*, QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#1  0x00007ffff76d014c in QV8Engine::fromVariant(QVariant const&) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#2  0x00007ffff76c03d2 in QV4::QmlContextWrapper::get(QV4::Managed*, QV4::String*, bool*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#3  0x00007ffff75a191a in QV4::ExecutionContext::getProperty(QV4::String*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#4  0x00007fffdd7a957a in ?? ()
#5  0x00007ffff67ff450 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x0000000000622300 in ?? ()
#7  0x00007fffdd8fc820 in ?? ()
#8  0x0000000000622301 in ?? ()
#9  0x00007ffff67ff450 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x0000000000622300 in ?? ()
#11 0x0000000000827430 in ?? ()
#12 0x0000000000827430 in ?? ()
#13 0x00007fffdd98b000 in ?? ()
#14 0x00007ffff75ce936 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#15 0x00007ffff76b3c8f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#16 0x00007ffff76b4196 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#17 0x00007ffff76bc489 in QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#18 0x00007ffff76bcc7e in QQmlBinding::expressionChanged(QQmlJavaScriptExpression*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#19 0x00007ffff7696497 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#20 0x00007ffff763310c in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#21 0x00007ffff65cf141 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff762cd2d in QQmlVMEMetaObject::writeVarProperty(int, QV4::ValueRef) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#23 0x00007ffff7647ab4 in QQmlPropertyPrivate::writeBinding(QObject*, QQmlPropertyData const&, QQmlContextData*, QQmlJavaScriptExpression*, QV4::ValueRef, bool, QFlags<QQmlPropertyPrivate::WriteFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#24 0x00007ffff76bc51c in QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#25 0x00007ffff76bcc7e in QQmlBinding::expressionChanged(QQmlJavaScriptExpression*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#26 0x00007ffff7696497 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#27 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#28 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#29 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#30 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#31 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#32 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#33 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#34 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#35 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#36 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#37 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#38 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#39 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#40 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#41 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#42 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#43 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#44 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#45 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#46 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#47 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#48 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#49 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#50 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#51 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#52 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#53 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#54 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#55 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#56 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#57 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#58 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#59 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#60 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#61 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#62 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#63 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#64 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#65 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#66 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#67 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#68 0x00007ffff769645e in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#69 0x00007ffff763310c in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#70 0x00007ffff65cf141 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#71 0x00007ffff7907324 in KDSME::StateMachineScene::rootStateChanged (this=0xa8d4d0, _t1=0x1538b40) at /home/brett/KDStateMachineEditor/build/src/view/moc_statemachinescene.cpp:310
#72 0x00007ffff78f8c67 in KDSME::StateMachineScene::setRootState (this=0xa8d4d0, rootState=0x1538b40) at /home/brett/KDStateMachineEditor/src/view/statemachinescene.cpp:170
#73 0x000000000040bc35 in MainWindow::setStateMachine (this=0x7fffffffdf00, stateMachine=0x1538b40) at /home/brett/KDStateMachineEditor/src/app/mainwindow.cpp:174
#74 0x000000000040be46 in MainWindow::createNew (this=0x7fffffffdf00) at /home/brett/KDStateMachineEditor/src/app/mainwindow.cpp:197
#75 0x0000000000411642 in MainWindow::qt_static_metacall (_o=0x7fffffffdf00, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffd0d0) at /home/brett/KDStateMachineEditor/build/src/app/moc_mainwindow.cpp:92
#76 0x00007ffff65cf9c9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#77 0x00007ffff6e9e722 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#78 0x00007ffff6ea0e28 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#79 0x00007ffff6fa523d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#80 0x00007ffff6fa5454 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#81 0x00007ffff707123a in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#82 0x00007ffff6eec1e8 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#83 0x00007ffff7071319 in QToolButton::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#84 0x00007ffff6ea8b2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#85 0x00007ffff6eae8eb in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#86 0x00007ffff659ec2b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#87 0x00007ffff6ead3da in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#88 0x00007ffff6f04cc0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#89 0x00007ffff6f06e33 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#90 0x00007ffff6ea8b2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#91 0x00007ffff6eae000 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#92 0x00007ffff659ec2b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#93 0x00007ffff68ebf82 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#94 0x00007ffff68edb45 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#95 0x00007ffff68d234f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#96 0x00007fffedecb590 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#97 0x00007ffff44e1c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#98 0x00007ffff44e1f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#99 0x00007ffff44e1fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#100 0x00007ffff65f7c57 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#101 0x00007ffff659c3e2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#102 0x00007ffff65a402c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#103 0x00000000004112f7 in main (argc=1, argv=0x7fffffffe058) at /home/brett/KDStateMachineEditor/src/app/main.cpp:87
```

Some additional info:

```
Linux LameServer 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by krf** [comment]
Cannot reproduce, please reopen if this shows up again.
